apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: <YOUR-ACCESS-KEY-ID>
  secretAccessKey: <YOUR-SECRET-ACCESS-KEY>
  endpoint: <YOUR-ENDPOINT> # e.g.: http://minio.messager.svc.cluster.local:9000
  region: <YOUR-REGION>